syntax = "proto3";

package aoyorouter.docs.api.v1;
import "google/protobuf/timestamp.proto";

option go_package = "github.com/yawaflua/aoyorouter/pkg/pb/api/aoyorouter;aoyorouter";

message HealthCheckResponse {
    string status = 1;
    repeated string issues = 2;
}

message SignInRequest {
    string password = 2;
}
message SignInResponse {
    string status = 1;
    string auth_token = 2;
}

message CreateProviderRequest {
    string name = 1;
    ProviderType type = 2;
    string client_id = 3;
    string client_secret = 4;
    bool use_proxy = 5;
    string proxy = 6;
    int32 priority = 7;
}
message CreateProviderResponse {
    string status = 1;
    string provider_id = 2;
}

message CreateProviderAuthorizationRequest {
    string name = 1;
    ProviderType type = 2;
    string custom_url = 3;
    bool use_proxy = 7;
    string proxy = 8;
    int32 priority = 9;
}

message CreateProviderAuthorizationResponse {
    string authorization_url = 1;
    string state = 2;
    string provider_id = 3;
    string flow = 4;
    string user_code = 5;
    int32 expires_in = 6;
}

message CompleteProviderAuthorizationRequest {
    string state = 1;
    string callback_url = 2;
    ProviderType type = 4;
    bool use_proxy = 3;
    string proxy = 5;
}

message GetProviderAuthorizationStatusRequest {
    string state = 1;
    bool use_proxy = 2;
    string proxy = 3;
}

message ProviderAuthorizationStatusResponse {
    string status = 1;
    string provider_id = 2;
    string error = 3;
}

enum ProviderType {
    PROVIDER_TYPE_UNSPECIFIED = 0;
    PROVIDER_TYPE_CUSTOM = 1;
    PROVIDER_TYPE_OPENAI = 2;
    PROVIDER_TYPE_ANTHROPIC = 3;
    PROVIDER_TYPE_KIMI = 4;
    PROVIDER_TYPE_GROK = 5;
    PROVIDER_TYPE_ANTIGRAVITY = 6;
    PROVIDER_TYPE_OPENCODE_ZEN = 7;
    PROVIDER_TYPE_OPENCODE_GO = 8;
    PROVIDER_TYPE_CLINE = 9;
}

message ProviderQuotaWindow {
    string name = 1;
    double used_percent = 2;
    string resets_at = 3;
    int32 window_minutes = 4;
}

message ProviderQuota {
    repeated ProviderQuotaWindow quotas = 1;
    string plan_type = 3;
    string error = 4;
}

message Provider {
    string id = 1;
    string name = 2;
    ProviderType type = 3;
    string client_id = 4;
    string client_secret = 5;
    ProviderQuota quota = 6;
    bool use_proxy = 7;
    string proxy = 8;
    bool is_cloudflare = 9;
    int32 priority = 10;
    bool disabled = 11;
}

message GetProviderRequest {
    string provider_id = 1;
}
message GetProviderResponse {
    Provider provider = 1;
}

message GetProvidersListRequest {

}
message GetProvidersListResponse {
    repeated Provider providers = 1;
}

message UpdateProviderRequest {
    string provider_id = 1;
    string name = 2;
    ProviderType type = 3;
    string client_id = 4;
    string client_secret = 5;
    bool use_proxy = 6;
    string proxy = 7;
    int32 priority = 8;
    bool disabled = 9;
    bool is_cloudflare = 10;
}
message UpdateProviderResponse {
    string status = 1;
}

message DeleteProviderRequest {
    string provider_id = 1;
}
message DeleteProviderResponse {
    string status = 1;
}

message CreateApiKeyRequest {
    string name = 1;
    string is_admin = 2;
}
message CreateApiKeyResponse {
    string status = 1;
    string api_key = 2;
    string api_key_id = 3;
}

message DeleteApiKeyRequest {
    string api_key_id = 1;
}
message DeleteApiKeyResponse {
    string status = 1;
}

message EditApiKeyRequest {
    string api_key_id = 1;
    ApiKey api_key = 2;
}
message EditApiKeyResponse {
    string status = 1;
}

message GetApiKeyListRequest {
}
message GetApiKeyListResponse {
    repeated ApiKey api_keys = 1;
}

message ApiKey {
    string id = 1;
    string name = 2;
    string is_admin = 3;
    bool is_active = 4;
    bool quota_setted = 5;
    int64 reserved_tokens = 6;
    google.protobuf.Timestamp quota_reset_at = 7;
    QuotaResetStrategy quota_reset_strategy = 8;
    int64 quota_used = 9;
    repeated string restricted_providers = 10;
    repeated string restricted_models = 11;
}

enum QuotaResetStrategy {
    QUOTA_RESET_STRATEGY_UNSPECIFIED = 0;
    QUOTA_RESET_STRATEGY_MINUTES = 1;
    QUOTA_RESET_STRATEGY_HOURLY = 2;
    QUOTA_RESET_STRATEGY_DAILY = 3;
    QUOTA_RESET_STRATEGY_WEEKLY = 4;
    QUOTA_RESET_STRATEGY_MONTHLY = 5;
    QUOTA_RESET_STRATEGY_FOREVER = 6;
}

message LogEntry {
    string provider = 1;
    string api_key_id = 2;
    int64 latency = 3;
    int64 input_tokens = 4;
    int64 output_tokens = 5;
    int64 total_tokens = 6;
    int64 cached_tokens = 7;
    string model = 8;
    string reasoning_effort = 9;
    bool failed = 10;
    string error = 11;
    google.protobuf.Timestamp request_time = 12;
    google.protobuf.Timestamp created_at = 13;
}

message GetUsageLogsRequest {
    int32 limit = 2;
    int32 offset = 3;
}
message GetProviderLogsByKeyIDRequest {
    string api_key_id = 1;
}
message GetProviderLogsByKeyIDResponse {
    repeated LogEntry logs = 1;
    int64 total_tokens = 2;
}

message GetUsageLogsResponse {
    repeated LogEntry logs = 1;
}

message GetProxiesRequest {
}
message GetProxiesResponse {
    repeated Proxy proxies = 1;
    repeated ProxyEndpoint available_endpoints = 2;
}

message ProxyEndpoint {
    string addr = 1;
    string rtt = 2;
}

message UpdateProxyRequest {
    string proxy_id = 1;
    string cloudflare_endpoint = 3;
    string new_endpoint = 4;
}
message UpdateProxyResponse {
    Proxy proxy = 1;
    string status = 2;
}
message Proxy {
    string id = 1;
    string name = 2;
    string url = 3;
    string cloudflare_addr = 4;
    WARPInfo warp_info = 5;
}

message WARPInfo {
    string ip = 1;
    string http_type = 2;
    string server_city = 3;
    string server_location = 4;
    string tls = 5;
}
