volumes:
  psql:
    driver: local

services:
  psql:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - psql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  aoyorouter:
    image: ghcr.io/yawaflua/aoyorouter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-psql}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_SSL=${POSTGRES_SSL:-disable}
      - INITIAL_PASSWORD=${INITIAL_PASSWORD:-}
    depends_on:
      psql:
        condition: service_healthy
