version: "3"

tasks:
  protoc:
    desc: "generate go files from protos"
    cmds:
      - mkdir -p ./pkg/pb/api/aoyorouter

      - protoc
        --go_out=./pkg/pb/api/aoyorouter
        --go_opt=paths=source_relative
        --go-grpc_out=./pkg/pb/api/aoyorouter
        --go-grpc_opt=paths=source_relative
        -I . --grpc-gateway_out ./pkg/pb/api/aoyorouter
        --grpc-gateway_opt=paths=source_relative
        --experimental_allow_proto3_optional
        ./docs/api/v1/*.proto

  protoc-swag:
    desc: "generate swagger from proto"
    cmds:
      - protoc -I . --openapiv2_out=./docs/  ./docs/api/v1/*.proto

      - mv ./docs/docs/api/v1/* ./docs/api/v1/
      - rm -rf ./docs/docs

  
  goose-up:
    desc: "run goose up"
    dotenv: [".env"]
    cmds:
      - goose -dir ./migrations postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=$POSTGRES_SSL" up
  goose-down:
    desc: "run goose down"
    dotenv: [".env"]
    cmds:
      - goose -dir ./migrations postgres "host=$POSTGRES_HOST user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_PORT sslmode=$POSTGRES_SSL" down