// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: docs/api/v1/project.proto

package aoyorouter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AoyoRouterService_HealthCheck_FullMethodName      = "/aoyorouter.docs.api.v1.AoyoRouterService/HealthCheck"
	AoyoRouterService_SignIn_FullMethodName           = "/aoyorouter.docs.api.v1.AoyoRouterService/SignIn"
	AoyoRouterService_CreateProvider_FullMethodName   = "/aoyorouter.docs.api.v1.AoyoRouterService/CreateProvider"
	AoyoRouterService_GetProvider_FullMethodName      = "/aoyorouter.docs.api.v1.AoyoRouterService/GetProvider"
	AoyoRouterService_GetProvidersList_FullMethodName = "/aoyorouter.docs.api.v1.AoyoRouterService/GetProvidersList"
	AoyoRouterService_UpdateProvider_FullMethodName   = "/aoyorouter.docs.api.v1.AoyoRouterService/UpdateProvider"
	AoyoRouterService_DeleteProvider_FullMethodName   = "/aoyorouter.docs.api.v1.AoyoRouterService/DeleteProvider"
	AoyoRouterService_CreateApiKey_FullMethodName     = "/aoyorouter.docs.api.v1.AoyoRouterService/CreateApiKey"
	AoyoRouterService_DeleteApiKey_FullMethodName     = "/aoyorouter.docs.api.v1.AoyoRouterService/DeleteApiKey"
	AoyoRouterService_GetApiKeyList_FullMethodName    = "/aoyorouter.docs.api.v1.AoyoRouterService/GetApiKeyList"
	AoyoRouterService_GetProviderLogs_FullMethodName  = "/aoyorouter.docs.api.v1.AoyoRouterService/GetProviderLogs"
)

// AoyoRouterServiceClient is the client API for AoyoRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AoyoRouterServiceClient interface {
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error)
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error)
	GetProvidersList(ctx context.Context, in *GetProvidersListRequest, opts ...grpc.CallOption) (*GetProvidersListResponse, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error)
	CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error)
	DeleteApiKey(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error)
	GetApiKeyList(ctx context.Context, in *GetApiKeyListRequest, opts ...grpc.CallOption) (*GetApiKeyListResponse, error)
	GetProviderLogs(ctx context.Context, in *GetProviderLogsRequest, opts ...grpc.CallOption) (*GetProviderLogsResponse, error)
}

type aoyoRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAoyoRouterServiceClient(cc grpc.ClientConnInterface) AoyoRouterServiceClient {
	return &aoyoRouterServiceClient{cc}
}

func (c *aoyoRouterServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_SignIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProviderResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*GetProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) GetProvidersList(ctx context.Context, in *GetProvidersListRequest, opts ...grpc.CallOption) (*GetProvidersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvidersListResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_GetProvidersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProviderResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApiKeyResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_CreateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) DeleteApiKey(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApiKeyResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_DeleteApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) GetApiKeyList(ctx context.Context, in *GetApiKeyListRequest, opts ...grpc.CallOption) (*GetApiKeyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiKeyListResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_GetApiKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aoyoRouterServiceClient) GetProviderLogs(ctx context.Context, in *GetProviderLogsRequest, opts ...grpc.CallOption) (*GetProviderLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderLogsResponse)
	err := c.cc.Invoke(ctx, AoyoRouterService_GetProviderLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AoyoRouterServiceServer is the server API for AoyoRouterService service.
// All implementations must embed UnimplementedAoyoRouterServiceServer
// for forward compatibility.
type AoyoRouterServiceServer interface {
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error)
	GetProvider(context.Context, *GetProviderRequest) (*GetProviderResponse, error)
	GetProvidersList(context.Context, *GetProvidersListRequest) (*GetProvidersListResponse, error)
	UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error)
	DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error)
	CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error)
	DeleteApiKey(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error)
	GetApiKeyList(context.Context, *GetApiKeyListRequest) (*GetApiKeyListResponse, error)
	GetProviderLogs(context.Context, *GetProviderLogsRequest) (*GetProviderLogsResponse, error)
	mustEmbedUnimplementedAoyoRouterServiceServer()
}

// UnimplementedAoyoRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAoyoRouterServiceServer struct{}

func (UnimplementedAoyoRouterServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAoyoRouterServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedAoyoRouterServiceServer) CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedAoyoRouterServiceServer) GetProvider(context.Context, *GetProviderRequest) (*GetProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedAoyoRouterServiceServer) GetProvidersList(context.Context, *GetProvidersListRequest) (*GetProvidersListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProvidersList not implemented")
}
func (UnimplementedAoyoRouterServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedAoyoRouterServiceServer) DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedAoyoRouterServiceServer) CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApiKey not implemented")
}
func (UnimplementedAoyoRouterServiceServer) DeleteApiKey(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApiKey not implemented")
}
func (UnimplementedAoyoRouterServiceServer) GetApiKeyList(context.Context, *GetApiKeyListRequest) (*GetApiKeyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApiKeyList not implemented")
}
func (UnimplementedAoyoRouterServiceServer) GetProviderLogs(context.Context, *GetProviderLogsRequest) (*GetProviderLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderLogs not implemented")
}
func (UnimplementedAoyoRouterServiceServer) mustEmbedUnimplementedAoyoRouterServiceServer() {}
func (UnimplementedAoyoRouterServiceServer) testEmbeddedByValue()                           {}

// UnsafeAoyoRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AoyoRouterServiceServer will
// result in compilation errors.
type UnsafeAoyoRouterServiceServer interface {
	mustEmbedUnimplementedAoyoRouterServiceServer()
}

func RegisterAoyoRouterServiceServer(s grpc.ServiceRegistrar, srv AoyoRouterServiceServer) {
	// If the following call panics, it indicates UnimplementedAoyoRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AoyoRouterService_ServiceDesc, srv)
}

func _AoyoRouterService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_SignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).CreateProvider(ctx, req.(*CreateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_GetProvidersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).GetProvidersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_GetProvidersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).GetProvidersList(ctx, req.(*GetProvidersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).DeleteProvider(ctx, req.(*DeleteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_CreateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).CreateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_CreateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).CreateApiKey(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_DeleteApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).DeleteApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_DeleteApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).DeleteApiKey(ctx, req.(*DeleteApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_GetApiKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiKeyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).GetApiKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_GetApiKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).GetApiKeyList(ctx, req.(*GetApiKeyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AoyoRouterService_GetProviderLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AoyoRouterServiceServer).GetProviderLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AoyoRouterService_GetProviderLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AoyoRouterServiceServer).GetProviderLogs(ctx, req.(*GetProviderLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AoyoRouterService_ServiceDesc is the grpc.ServiceDesc for AoyoRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AoyoRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aoyorouter.docs.api.v1.AoyoRouterService",
	HandlerType: (*AoyoRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AoyoRouterService_HealthCheck_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _AoyoRouterService_SignIn_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _AoyoRouterService_CreateProvider_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _AoyoRouterService_GetProvider_Handler,
		},
		{
			MethodName: "GetProvidersList",
			Handler:    _AoyoRouterService_GetProvidersList_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _AoyoRouterService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _AoyoRouterService_DeleteProvider_Handler,
		},
		{
			MethodName: "CreateApiKey",
			Handler:    _AoyoRouterService_CreateApiKey_Handler,
		},
		{
			MethodName: "DeleteApiKey",
			Handler:    _AoyoRouterService_DeleteApiKey_Handler,
		},
		{
			MethodName: "GetApiKeyList",
			Handler:    _AoyoRouterService_GetApiKeyList_Handler,
		},
		{
			MethodName: "GetProviderLogs",
			Handler:    _AoyoRouterService_GetProviderLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/api/v1/project.proto",
}
