// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: docs/api/v1/project.proto

package aoyorouter

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_docs_api_v1_project_proto protoreflect.FileDescriptor

const file_docs_api_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x19docs/api/v1/project.proto\x12\x16aoyorouter.docs.api.v1\x1a\x17docs/api/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\x99\x16\n" +
	"\x11AoyoRouterService\x12p\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a+.aoyorouter.docs.api.v1.HealthCheckResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/aoyo/v1/healthz\x12w\n" +
	"\x06SignIn\x12%.aoyorouter.docs.api.v1.SignInRequest\x1a&.aoyorouter.docs.api.v1.SignInResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/aoyo/v1/signin\x12\x92\x01\n" +
	"\x0eCreateProvider\x12-.aoyorouter.docs.api.v1.CreateProviderRequest\x1a..aoyorouter.docs.api.v1.CreateProviderResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/aoyo/v1/providers\x12\xc3\x01\n" +
	"\x1bCreateProviderAuthorization\x12:.aoyorouter.docs.api.v1.CreateProviderAuthorizationRequest\x1a;.aoyorouter.docs.api.v1.CreateProviderAuthorizationResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/aoyo/v1/providers/authorize\x12\xd0\x01\n" +
	"\x1dCompleteProviderAuthorization\x12<.aoyorouter.docs.api.v1.CompleteProviderAuthorizationRequest\x1a;.aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/aoyo/v1/providers/authorize/complete\x12\xce\x01\n" +
	"\x1eGetProviderAuthorizationStatus\x12=.aoyorouter.docs.api.v1.GetProviderAuthorizationStatusRequest\x1a;.aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/aoyo/v1/providers/authorize/{state}\x12\x94\x01\n" +
	"\vGetProvider\x12*.aoyorouter.docs.api.v1.GetProviderRequest\x1a+.aoyorouter.docs.api.v1.GetProviderResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/aoyo/v1/providers/{provider_id}\x12\x95\x01\n" +
	"\x10GetProvidersList\x12/.aoyorouter.docs.api.v1.GetProvidersListRequest\x1a0.aoyorouter.docs.api.v1.GetProvidersListResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/aoyo/v1/providers\x12\xa0\x01\n" +
	"\x0eUpdateProvider\x12-.aoyorouter.docs.api.v1.UpdateProviderRequest\x1a..aoyorouter.docs.api.v1.UpdateProviderResponse\"/\x82\xd3\xe4\x93\x02):\x01*2$/api/aoyo/v1/providers/{provider_id}\x12\x9d\x01\n" +
	"\x0eDeleteProvider\x12-.aoyorouter.docs.api.v1.DeleteProviderRequest\x1a..aoyorouter.docs.api.v1.DeleteProviderResponse\",\x82\xd3\xe4\x93\x02&*$/api/aoyo/v1/providers/{provider_id}\x12\x8b\x01\n" +
	"\fCreateApiKey\x12+.aoyorouter.docs.api.v1.CreateApiKeyRequest\x1a,.aoyorouter.docs.api.v1.CreateApiKeyResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/aoyo/v1/api-keys\x12\x92\x01\n" +
	"\n" +
	"EditApiKey\x12).aoyorouter.docs.api.v1.EditApiKeyRequest\x1a*.aoyorouter.docs.api.v1.EditApiKeyResponse\"-\x82\xd3\xe4\x93\x02':\x01*2\"/api/aoyo/v1/api-keys/{api_key_id}\x12\x95\x01\n" +
	"\fDeleteApiKey\x12+.aoyorouter.docs.api.v1.DeleteApiKeyRequest\x1a,.aoyorouter.docs.api.v1.DeleteApiKeyResponse\"*\x82\xd3\xe4\x93\x02$*\"/api/aoyo/v1/api-keys/{api_key_id}\x12\x8b\x01\n" +
	"\rGetApiKeyList\x12,.aoyorouter.docs.api.v1.GetApiKeyListRequest\x1a-.aoyorouter.docs.api.v1.GetApiKeyListResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/aoyo/v1/api-keys\x12\x8a\x01\n" +
	"\fGetUsageLogs\x12+.aoyorouter.docs.api.v1.GetUsageLogsRequest\x1a,.aoyorouter.docs.api.v1.GetUsageLogsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/aoyo/v1/usage/logs\x12\xb8\x01\n" +
	"\x16GetProviderLogsByKeyID\x125.aoyorouter.docs.api.v1.GetProviderLogsByKeyIDRequest\x1a6.aoyorouter.docs.api.v1.GetProviderLogsByKeyIDResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/aoyo/v1/api-keys/{api_key_id}/logs\x12\x81\x01\n" +
	"\n" +
	"GetProxies\x12).aoyorouter.docs.api.v1.GetProxiesRequest\x1a*.aoyorouter.docs.api.v1.GetProxiesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/aoyo/v1/proxies\x12\x92\x01\n" +
	"\vUpdateProxy\x12*.aoyorouter.docs.api.v1.UpdateProxyRequest\x1a+.aoyorouter.docs.api.v1.UpdateProxyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*2\x1f/api/aoyo/v1/proxies/{proxy_id}BAZ?github.com/yawaflua/aoyorouter/pkg/pb/api/aoyorouter;aoyorouterb\x06proto3"

var file_docs_api_v1_project_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                         // 0: google.protobuf.Empty
	(*SignInRequest)(nil),                         // 1: aoyorouter.docs.api.v1.SignInRequest
	(*CreateProviderRequest)(nil),                 // 2: aoyorouter.docs.api.v1.CreateProviderRequest
	(*CreateProviderAuthorizationRequest)(nil),    // 3: aoyorouter.docs.api.v1.CreateProviderAuthorizationRequest
	(*CompleteProviderAuthorizationRequest)(nil),  // 4: aoyorouter.docs.api.v1.CompleteProviderAuthorizationRequest
	(*GetProviderAuthorizationStatusRequest)(nil), // 5: aoyorouter.docs.api.v1.GetProviderAuthorizationStatusRequest
	(*GetProviderRequest)(nil),                    // 6: aoyorouter.docs.api.v1.GetProviderRequest
	(*GetProvidersListRequest)(nil),               // 7: aoyorouter.docs.api.v1.GetProvidersListRequest
	(*UpdateProviderRequest)(nil),                 // 8: aoyorouter.docs.api.v1.UpdateProviderRequest
	(*DeleteProviderRequest)(nil),                 // 9: aoyorouter.docs.api.v1.DeleteProviderRequest
	(*CreateApiKeyRequest)(nil),                   // 10: aoyorouter.docs.api.v1.CreateApiKeyRequest
	(*EditApiKeyRequest)(nil),                     // 11: aoyorouter.docs.api.v1.EditApiKeyRequest
	(*DeleteApiKeyRequest)(nil),                   // 12: aoyorouter.docs.api.v1.DeleteApiKeyRequest
	(*GetApiKeyListRequest)(nil),                  // 13: aoyorouter.docs.api.v1.GetApiKeyListRequest
	(*GetUsageLogsRequest)(nil),                   // 14: aoyorouter.docs.api.v1.GetUsageLogsRequest
	(*GetProviderLogsByKeyIDRequest)(nil),         // 15: aoyorouter.docs.api.v1.GetProviderLogsByKeyIDRequest
	(*GetProxiesRequest)(nil),                     // 16: aoyorouter.docs.api.v1.GetProxiesRequest
	(*UpdateProxyRequest)(nil),                    // 17: aoyorouter.docs.api.v1.UpdateProxyRequest
	(*HealthCheckResponse)(nil),                   // 18: aoyorouter.docs.api.v1.HealthCheckResponse
	(*SignInResponse)(nil),                        // 19: aoyorouter.docs.api.v1.SignInResponse
	(*CreateProviderResponse)(nil),                // 20: aoyorouter.docs.api.v1.CreateProviderResponse
	(*CreateProviderAuthorizationResponse)(nil),   // 21: aoyorouter.docs.api.v1.CreateProviderAuthorizationResponse
	(*ProviderAuthorizationStatusResponse)(nil),   // 22: aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse
	(*GetProviderResponse)(nil),                   // 23: aoyorouter.docs.api.v1.GetProviderResponse
	(*GetProvidersListResponse)(nil),              // 24: aoyorouter.docs.api.v1.GetProvidersListResponse
	(*UpdateProviderResponse)(nil),                // 25: aoyorouter.docs.api.v1.UpdateProviderResponse
	(*DeleteProviderResponse)(nil),                // 26: aoyorouter.docs.api.v1.DeleteProviderResponse
	(*CreateApiKeyResponse)(nil),                  // 27: aoyorouter.docs.api.v1.CreateApiKeyResponse
	(*EditApiKeyResponse)(nil),                    // 28: aoyorouter.docs.api.v1.EditApiKeyResponse
	(*DeleteApiKeyResponse)(nil),                  // 29: aoyorouter.docs.api.v1.DeleteApiKeyResponse
	(*GetApiKeyListResponse)(nil),                 // 30: aoyorouter.docs.api.v1.GetApiKeyListResponse
	(*GetUsageLogsResponse)(nil),                  // 31: aoyorouter.docs.api.v1.GetUsageLogsResponse
	(*GetProviderLogsByKeyIDResponse)(nil),        // 32: aoyorouter.docs.api.v1.GetProviderLogsByKeyIDResponse
	(*GetProxiesResponse)(nil),                    // 33: aoyorouter.docs.api.v1.GetProxiesResponse
	(*UpdateProxyResponse)(nil),                   // 34: aoyorouter.docs.api.v1.UpdateProxyResponse
}
var file_docs_api_v1_project_proto_depIdxs = []int32{
	0,  // 0: aoyorouter.docs.api.v1.AoyoRouterService.HealthCheck:input_type -> google.protobuf.Empty
	1,  // 1: aoyorouter.docs.api.v1.AoyoRouterService.SignIn:input_type -> aoyorouter.docs.api.v1.SignInRequest
	2,  // 2: aoyorouter.docs.api.v1.AoyoRouterService.CreateProvider:input_type -> aoyorouter.docs.api.v1.CreateProviderRequest
	3,  // 3: aoyorouter.docs.api.v1.AoyoRouterService.CreateProviderAuthorization:input_type -> aoyorouter.docs.api.v1.CreateProviderAuthorizationRequest
	4,  // 4: aoyorouter.docs.api.v1.AoyoRouterService.CompleteProviderAuthorization:input_type -> aoyorouter.docs.api.v1.CompleteProviderAuthorizationRequest
	5,  // 5: aoyorouter.docs.api.v1.AoyoRouterService.GetProviderAuthorizationStatus:input_type -> aoyorouter.docs.api.v1.GetProviderAuthorizationStatusRequest
	6,  // 6: aoyorouter.docs.api.v1.AoyoRouterService.GetProvider:input_type -> aoyorouter.docs.api.v1.GetProviderRequest
	7,  // 7: aoyorouter.docs.api.v1.AoyoRouterService.GetProvidersList:input_type -> aoyorouter.docs.api.v1.GetProvidersListRequest
	8,  // 8: aoyorouter.docs.api.v1.AoyoRouterService.UpdateProvider:input_type -> aoyorouter.docs.api.v1.UpdateProviderRequest
	9,  // 9: aoyorouter.docs.api.v1.AoyoRouterService.DeleteProvider:input_type -> aoyorouter.docs.api.v1.DeleteProviderRequest
	10, // 10: aoyorouter.docs.api.v1.AoyoRouterService.CreateApiKey:input_type -> aoyorouter.docs.api.v1.CreateApiKeyRequest
	11, // 11: aoyorouter.docs.api.v1.AoyoRouterService.EditApiKey:input_type -> aoyorouter.docs.api.v1.EditApiKeyRequest
	12, // 12: aoyorouter.docs.api.v1.AoyoRouterService.DeleteApiKey:input_type -> aoyorouter.docs.api.v1.DeleteApiKeyRequest
	13, // 13: aoyorouter.docs.api.v1.AoyoRouterService.GetApiKeyList:input_type -> aoyorouter.docs.api.v1.GetApiKeyListRequest
	14, // 14: aoyorouter.docs.api.v1.AoyoRouterService.GetUsageLogs:input_type -> aoyorouter.docs.api.v1.GetUsageLogsRequest
	15, // 15: aoyorouter.docs.api.v1.AoyoRouterService.GetProviderLogsByKeyID:input_type -> aoyorouter.docs.api.v1.GetProviderLogsByKeyIDRequest
	16, // 16: aoyorouter.docs.api.v1.AoyoRouterService.GetProxies:input_type -> aoyorouter.docs.api.v1.GetProxiesRequest
	17, // 17: aoyorouter.docs.api.v1.AoyoRouterService.UpdateProxy:input_type -> aoyorouter.docs.api.v1.UpdateProxyRequest
	18, // 18: aoyorouter.docs.api.v1.AoyoRouterService.HealthCheck:output_type -> aoyorouter.docs.api.v1.HealthCheckResponse
	19, // 19: aoyorouter.docs.api.v1.AoyoRouterService.SignIn:output_type -> aoyorouter.docs.api.v1.SignInResponse
	20, // 20: aoyorouter.docs.api.v1.AoyoRouterService.CreateProvider:output_type -> aoyorouter.docs.api.v1.CreateProviderResponse
	21, // 21: aoyorouter.docs.api.v1.AoyoRouterService.CreateProviderAuthorization:output_type -> aoyorouter.docs.api.v1.CreateProviderAuthorizationResponse
	22, // 22: aoyorouter.docs.api.v1.AoyoRouterService.CompleteProviderAuthorization:output_type -> aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse
	22, // 23: aoyorouter.docs.api.v1.AoyoRouterService.GetProviderAuthorizationStatus:output_type -> aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse
	23, // 24: aoyorouter.docs.api.v1.AoyoRouterService.GetProvider:output_type -> aoyorouter.docs.api.v1.GetProviderResponse
	24, // 25: aoyorouter.docs.api.v1.AoyoRouterService.GetProvidersList:output_type -> aoyorouter.docs.api.v1.GetProvidersListResponse
	25, // 26: aoyorouter.docs.api.v1.AoyoRouterService.UpdateProvider:output_type -> aoyorouter.docs.api.v1.UpdateProviderResponse
	26, // 27: aoyorouter.docs.api.v1.AoyoRouterService.DeleteProvider:output_type -> aoyorouter.docs.api.v1.DeleteProviderResponse
	27, // 28: aoyorouter.docs.api.v1.AoyoRouterService.CreateApiKey:output_type -> aoyorouter.docs.api.v1.CreateApiKeyResponse
	28, // 29: aoyorouter.docs.api.v1.AoyoRouterService.EditApiKey:output_type -> aoyorouter.docs.api.v1.EditApiKeyResponse
	29, // 30: aoyorouter.docs.api.v1.AoyoRouterService.DeleteApiKey:output_type -> aoyorouter.docs.api.v1.DeleteApiKeyResponse
	30, // 31: aoyorouter.docs.api.v1.AoyoRouterService.GetApiKeyList:output_type -> aoyorouter.docs.api.v1.GetApiKeyListResponse
	31, // 32: aoyorouter.docs.api.v1.AoyoRouterService.GetUsageLogs:output_type -> aoyorouter.docs.api.v1.GetUsageLogsResponse
	32, // 33: aoyorouter.docs.api.v1.AoyoRouterService.GetProviderLogsByKeyID:output_type -> aoyorouter.docs.api.v1.GetProviderLogsByKeyIDResponse
	33, // 34: aoyorouter.docs.api.v1.AoyoRouterService.GetProxies:output_type -> aoyorouter.docs.api.v1.GetProxiesResponse
	34, // 35: aoyorouter.docs.api.v1.AoyoRouterService.UpdateProxy:output_type -> aoyorouter.docs.api.v1.UpdateProxyResponse
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_docs_api_v1_project_proto_init() }
func file_docs_api_v1_project_proto_init() {
	if File_docs_api_v1_project_proto != nil {
		return
	}
	file_docs_api_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_api_v1_project_proto_rawDesc), len(file_docs_api_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_api_v1_project_proto_goTypes,
		DependencyIndexes: file_docs_api_v1_project_proto_depIdxs,
	}.Build()
	File_docs_api_v1_project_proto = out.File
	file_docs_api_v1_project_proto_goTypes = nil
	file_docs_api_v1_project_proto_depIdxs = nil
}
