// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: docs/api/v1/types.proto

package aoyorouter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_CUSTOM      ProviderType = 1
	ProviderType_PROVIDER_TYPE_OPENAI      ProviderType = 2
	ProviderType_PROVIDER_TYPE_ANTHROPIC   ProviderType = 3
	ProviderType_PROVIDER_TYPE_KIMI        ProviderType = 4
	ProviderType_PROVIDER_TYPE_GROK        ProviderType = 5
	ProviderType_PROVIDER_TYPE_ANTIGRAVITY ProviderType = 6
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_CUSTOM",
		2: "PROVIDER_TYPE_OPENAI",
		3: "PROVIDER_TYPE_ANTHROPIC",
		4: "PROVIDER_TYPE_KIMI",
		5: "PROVIDER_TYPE_GROK",
		6: "PROVIDER_TYPE_ANTIGRAVITY",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_CUSTOM":      1,
		"PROVIDER_TYPE_OPENAI":      2,
		"PROVIDER_TYPE_ANTHROPIC":   3,
		"PROVIDER_TYPE_KIMI":        4,
		"PROVIDER_TYPE_GROK":        5,
		"PROVIDER_TYPE_ANTIGRAVITY": 6,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_api_v1_types_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_docs_api_v1_types_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{0}
}

type QuotaResetStrategy int32

const (
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_UNSPECIFIED QuotaResetStrategy = 0
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_MINUTES     QuotaResetStrategy = 1
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_HOURLY      QuotaResetStrategy = 2
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_DAILY       QuotaResetStrategy = 3
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_WEEKLY      QuotaResetStrategy = 4
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_MONTHLY     QuotaResetStrategy = 5
	QuotaResetStrategy_QUOTA_RESET_STRATEGY_FOREVER     QuotaResetStrategy = 6
)

// Enum value maps for QuotaResetStrategy.
var (
	QuotaResetStrategy_name = map[int32]string{
		0: "QUOTA_RESET_STRATEGY_UNSPECIFIED",
		1: "QUOTA_RESET_STRATEGY_MINUTES",
		2: "QUOTA_RESET_STRATEGY_HOURLY",
		3: "QUOTA_RESET_STRATEGY_DAILY",
		4: "QUOTA_RESET_STRATEGY_WEEKLY",
		5: "QUOTA_RESET_STRATEGY_MONTHLY",
		6: "QUOTA_RESET_STRATEGY_FOREVER",
	}
	QuotaResetStrategy_value = map[string]int32{
		"QUOTA_RESET_STRATEGY_UNSPECIFIED": 0,
		"QUOTA_RESET_STRATEGY_MINUTES":     1,
		"QUOTA_RESET_STRATEGY_HOURLY":      2,
		"QUOTA_RESET_STRATEGY_DAILY":       3,
		"QUOTA_RESET_STRATEGY_WEEKLY":      4,
		"QUOTA_RESET_STRATEGY_MONTHLY":     5,
		"QUOTA_RESET_STRATEGY_FOREVER":     6,
	}
)

func (x QuotaResetStrategy) Enum() *QuotaResetStrategy {
	p := new(QuotaResetStrategy)
	*p = x
	return p
}

func (x QuotaResetStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaResetStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_api_v1_types_proto_enumTypes[1].Descriptor()
}

func (QuotaResetStrategy) Type() protoreflect.EnumType {
	return &file_docs_api_v1_types_proto_enumTypes[1]
}

func (x QuotaResetStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuotaResetStrategy.Descriptor instead.
func (QuotaResetStrategy) EnumDescriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *SignInResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SignInResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,2,opt,name=type,proto3,enum=aoyorouter.docs.api.v1.ProviderType" json:"type,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	UseProxy      bool                   `protobuf:"varint,5,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *CreateProviderRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateProviderRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateProviderRequest) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *CreateProviderRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type CreateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProviderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProviderResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type CreateProviderAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,2,opt,name=type,proto3,enum=aoyorouter.docs.api.v1.ProviderType" json:"type,omitempty"`
	CustomUrl     string                 `protobuf:"bytes,3,opt,name=custom_url,json=customUrl,proto3" json:"custom_url,omitempty"`
	UseProxy      bool                   `protobuf:"varint,7,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,8,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderAuthorizationRequest) Reset() {
	*x = CreateProviderAuthorizationRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderAuthorizationRequest) ProtoMessage() {}

func (x *CreateProviderAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProviderAuthorizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderAuthorizationRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *CreateProviderAuthorizationRequest) GetCustomUrl() string {
	if x != nil {
		return x.CustomUrl
	}
	return ""
}

func (x *CreateProviderAuthorizationRequest) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *CreateProviderAuthorizationRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type CreateProviderAuthorizationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ProviderId       string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Flow             string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	UserCode         string                 `protobuf:"bytes,5,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	ExpiresIn        int32                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProviderAuthorizationResponse) Reset() {
	*x = CreateProviderAuthorizationResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderAuthorizationResponse) ProtoMessage() {}

func (x *CreateProviderAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProviderAuthorizationResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *CreateProviderAuthorizationResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateProviderAuthorizationResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateProviderAuthorizationResponse) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *CreateProviderAuthorizationResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *CreateProviderAuthorizationResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type CompleteProviderAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Type          ProviderType           `protobuf:"varint,4,opt,name=type,proto3,enum=aoyorouter.docs.api.v1.ProviderType" json:"type,omitempty"`
	UseProxy      bool                   `protobuf:"varint,3,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteProviderAuthorizationRequest) Reset() {
	*x = CompleteProviderAuthorizationRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProviderAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProviderAuthorizationRequest) ProtoMessage() {}

func (x *CompleteProviderAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProviderAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*CompleteProviderAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteProviderAuthorizationRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CompleteProviderAuthorizationRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *CompleteProviderAuthorizationRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *CompleteProviderAuthorizationRequest) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *CompleteProviderAuthorizationRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type GetProviderAuthorizationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	UseProxy      bool                   `protobuf:"varint,2,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,3,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderAuthorizationStatusRequest) Reset() {
	*x = GetProviderAuthorizationStatusRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderAuthorizationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderAuthorizationStatusRequest) ProtoMessage() {}

func (x *GetProviderAuthorizationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderAuthorizationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProviderAuthorizationStatusRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *GetProviderAuthorizationStatusRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetProviderAuthorizationStatusRequest) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *GetProviderAuthorizationStatusRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type ProviderAuthorizationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderAuthorizationStatusResponse) Reset() {
	*x = ProviderAuthorizationStatusResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderAuthorizationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderAuthorizationStatusResponse) ProtoMessage() {}

func (x *ProviderAuthorizationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderAuthorizationStatusResponse.ProtoReflect.Descriptor instead.
func (*ProviderAuthorizationStatusResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderAuthorizationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProviderAuthorizationStatusResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderAuthorizationStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProviderQuotaWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedPercent   float64                `protobuf:"fixed64,1,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	ResetsAt      string                 `protobuf:"bytes,2,opt,name=resets_at,json=resetsAt,proto3" json:"resets_at,omitempty"`
	WindowMinutes int32                  `protobuf:"varint,3,opt,name=window_minutes,json=windowMinutes,proto3" json:"window_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderQuotaWindow) Reset() {
	*x = ProviderQuotaWindow{}
	mi := &file_docs_api_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderQuotaWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderQuotaWindow) ProtoMessage() {}

func (x *ProviderQuotaWindow) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderQuotaWindow.ProtoReflect.Descriptor instead.
func (*ProviderQuotaWindow) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderQuotaWindow) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *ProviderQuotaWindow) GetResetsAt() string {
	if x != nil {
		return x.ResetsAt
	}
	return ""
}

func (x *ProviderQuotaWindow) GetWindowMinutes() int32 {
	if x != nil {
		return x.WindowMinutes
	}
	return 0
}

type ProviderQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       *ProviderQuotaWindow   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary     *ProviderQuotaWindow   `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	PlanType      string                 `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderQuota) Reset() {
	*x = ProviderQuota{}
	mi := &file_docs_api_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderQuota) ProtoMessage() {}

func (x *ProviderQuota) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderQuota.ProtoReflect.Descriptor instead.
func (*ProviderQuota) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderQuota) GetPrimary() *ProviderQuotaWindow {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *ProviderQuota) GetSecondary() *ProviderQuotaWindow {
	if x != nil {
		return x.Secondary
	}
	return nil
}

func (x *ProviderQuota) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *ProviderQuota) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,3,opt,name=type,proto3,enum=aoyorouter.docs.api.v1.ProviderType" json:"type,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Quota         *ProviderQuota         `protobuf:"bytes,6,opt,name=quota,proto3" json:"quota,omitempty"`
	UseProxy      bool                   `protobuf:"varint,7,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,8,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_docs_api_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *Provider) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Provider) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Provider) GetQuota() *ProviderQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *Provider) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *Provider) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *GetProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *GetProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type GetProvidersListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersListRequest) Reset() {
	*x = GetProvidersListRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersListRequest) ProtoMessage() {}

func (x *GetProvidersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersListRequest.ProtoReflect.Descriptor instead.
func (*GetProvidersListRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{15}
}

type GetProvidersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersListResponse) Reset() {
	*x = GetProvidersListResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersListResponse) ProtoMessage() {}

func (x *GetProvidersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersListResponse.ProtoReflect.Descriptor instead.
func (*GetProvidersListResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *GetProvidersListResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type UpdateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ProviderType           `protobuf:"varint,3,opt,name=type,proto3,enum=aoyorouter.docs.api.v1.ProviderType" json:"type,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	UseProxy      bool                   `protobuf:"varint,6,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	Proxy         string                 `protobuf:"bytes,7,opt,name=proxy,proto3" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *UpdateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProviderRequest) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *UpdateProviderRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateProviderRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *UpdateProviderRequest) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *UpdateProviderRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

type UpdateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderResponse) Reset() {
	*x = UpdateProviderResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderResponse) ProtoMessage() {}

func (x *UpdateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateProviderResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProviderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type DeleteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderResponse) Reset() {
	*x = DeleteProviderResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderResponse) ProtoMessage() {}

func (x *DeleteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteProviderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsAdmin       string                 `protobuf:"bytes,2,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{21}
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyRequest) GetIsAdmin() string {
	if x != nil {
		return x.IsAdmin
	}
	return ""
}

type CreateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{22}
}

func (x *CreateApiKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateApiKeyResponse) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type DeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRequest) Reset() {
	*x = DeleteApiKeyRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRequest) ProtoMessage() {}

func (x *DeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteApiKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type DeleteApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyResponse) Reset() {
	*x = DeleteApiKeyResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyResponse) ProtoMessage() {}

func (x *DeleteApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteApiKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EditApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ApiKey        *ApiKey                `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditApiKeyRequest) Reset() {
	*x = EditApiKeyRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditApiKeyRequest) ProtoMessage() {}

func (x *EditApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditApiKeyRequest.ProtoReflect.Descriptor instead.
func (*EditApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{25}
}

func (x *EditApiKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *EditApiKeyRequest) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type EditApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditApiKeyResponse) Reset() {
	*x = EditApiKeyResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditApiKeyResponse) ProtoMessage() {}

func (x *EditApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditApiKeyResponse.ProtoReflect.Descriptor instead.
func (*EditApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{26}
}

func (x *EditApiKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetApiKeyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyListRequest) Reset() {
	*x = GetApiKeyListRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyListRequest) ProtoMessage() {}

func (x *GetApiKeyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyListRequest.ProtoReflect.Descriptor instead.
func (*GetApiKeyListRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{27}
}

type GetApiKeyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyListResponse) Reset() {
	*x = GetApiKeyListResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyListResponse) ProtoMessage() {}

func (x *GetApiKeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyListResponse.ProtoReflect.Descriptor instead.
func (*GetApiKeyListResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{28}
}

func (x *GetApiKeyListResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type ApiKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsAdmin            string                 `protobuf:"bytes,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsActive           bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	QuotaSetted        bool                   `protobuf:"varint,5,opt,name=quota_setted,json=quotaSetted,proto3" json:"quota_setted,omitempty"`
	ReservedTokens     int64                  `protobuf:"varint,6,opt,name=reserved_tokens,json=reservedTokens,proto3" json:"reserved_tokens,omitempty"`
	QuotaResetAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=quota_reset_at,json=quotaResetAt,proto3" json:"quota_reset_at,omitempty"`
	QuotaResetStrategy QuotaResetStrategy     `protobuf:"varint,8,opt,name=quota_reset_strategy,json=quotaResetStrategy,proto3,enum=aoyorouter.docs.api.v1.QuotaResetStrategy" json:"quota_reset_strategy,omitempty"`
	QuotaUsed          int64                  `protobuf:"varint,9,opt,name=quota_used,json=quotaUsed,proto3" json:"quota_used,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_docs_api_v1_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{29}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetIsAdmin() string {
	if x != nil {
		return x.IsAdmin
	}
	return ""
}

func (x *ApiKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ApiKey) GetQuotaSetted() bool {
	if x != nil {
		return x.QuotaSetted
	}
	return false
}

func (x *ApiKey) GetReservedTokens() int64 {
	if x != nil {
		return x.ReservedTokens
	}
	return 0
}

func (x *ApiKey) GetQuotaResetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QuotaResetAt
	}
	return nil
}

func (x *ApiKey) GetQuotaResetStrategy() QuotaResetStrategy {
	if x != nil {
		return x.QuotaResetStrategy
	}
	return QuotaResetStrategy_QUOTA_RESET_STRATEGY_UNSPECIFIED
}

func (x *ApiKey) GetQuotaUsed() int64 {
	if x != nil {
		return x.QuotaUsed
	}
	return 0
}

type LogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ApiKeyId        string                 `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	Latency         int64                  `protobuf:"varint,3,opt,name=latency,proto3" json:"latency,omitempty"`
	InputTokens     int64                  `protobuf:"varint,4,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int64                  `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens     int64                  `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CachedTokens    int64                  `protobuf:"varint,7,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	Model           string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	ReasoningEffort string                 `protobuf:"bytes,9,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	Failed          bool                   `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`
	Error           string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	RequestTime     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_docs_api_v1_types_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{30}
}

func (x *LogEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LogEntry) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *LogEntry) GetLatency() int64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *LogEntry) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *LogEntry) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *LogEntry) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *LogEntry) GetCachedTokens() int64 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *LogEntry) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LogEntry) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *LogEntry) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *LogEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogEntry) GetRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

func (x *LogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetUsageLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageLogsRequest) Reset() {
	*x = GetUsageLogsRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLogsRequest) ProtoMessage() {}

func (x *GetUsageLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLogsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageLogsRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{31}
}

func (x *GetUsageLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsageLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetProviderLogsByKeyIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderLogsByKeyIDRequest) Reset() {
	*x = GetProviderLogsByKeyIDRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderLogsByKeyIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderLogsByKeyIDRequest) ProtoMessage() {}

func (x *GetProviderLogsByKeyIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderLogsByKeyIDRequest.ProtoReflect.Descriptor instead.
func (*GetProviderLogsByKeyIDRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{32}
}

func (x *GetProviderLogsByKeyIDRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

type GetProviderLogsByKeyIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderLogsByKeyIDResponse) Reset() {
	*x = GetProviderLogsByKeyIDResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderLogsByKeyIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderLogsByKeyIDResponse) ProtoMessage() {}

func (x *GetProviderLogsByKeyIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderLogsByKeyIDResponse.ProtoReflect.Descriptor instead.
func (*GetProviderLogsByKeyIDResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{33}
}

func (x *GetProviderLogsByKeyIDResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetProviderLogsByKeyIDResponse) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type GetUsageLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageLogsResponse) Reset() {
	*x = GetUsageLogsResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageLogsResponse) ProtoMessage() {}

func (x *GetUsageLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageLogsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageLogsResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{34}
}

func (x *GetUsageLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProxiesRequest) Reset() {
	*x = GetProxiesRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxiesRequest) ProtoMessage() {}

func (x *GetProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxiesRequest.ProtoReflect.Descriptor instead.
func (*GetProxiesRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{35}
}

type GetProxiesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Proxies            []*Proxy               `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	AvailableEndpoints []*ProxyEndpoint       `protobuf:"bytes,2,rep,name=available_endpoints,json=availableEndpoints,proto3" json:"available_endpoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProxiesResponse) Reset() {
	*x = GetProxiesResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProxiesResponse) ProtoMessage() {}

func (x *GetProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProxiesResponse.ProtoReflect.Descriptor instead.
func (*GetProxiesResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{36}
}

func (x *GetProxiesResponse) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *GetProxiesResponse) GetAvailableEndpoints() []*ProxyEndpoint {
	if x != nil {
		return x.AvailableEndpoints
	}
	return nil
}

type ProxyEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Rtt           string                 `protobuf:"bytes,2,opt,name=rtt,proto3" json:"rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyEndpoint) Reset() {
	*x = ProxyEndpoint{}
	mi := &file_docs_api_v1_types_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyEndpoint) ProtoMessage() {}

func (x *ProxyEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyEndpoint.ProtoReflect.Descriptor instead.
func (*ProxyEndpoint) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{37}
}

func (x *ProxyEndpoint) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ProxyEndpoint) GetRtt() string {
	if x != nil {
		return x.Rtt
	}
	return ""
}

type UpdateProxyRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProxyId            string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	CloudflareEndpoint string                 `protobuf:"bytes,3,opt,name=cloudflare_endpoint,json=cloudflareEndpoint,proto3" json:"cloudflare_endpoint,omitempty"`
	NewEndpoint        string                 `protobuf:"bytes,4,opt,name=new_endpoint,json=newEndpoint,proto3" json:"new_endpoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProxyRequest) Reset() {
	*x = UpdateProxyRequest{}
	mi := &file_docs_api_v1_types_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyRequest) ProtoMessage() {}

func (x *UpdateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxyRequest) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{38}
}

func (x *UpdateProxyRequest) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *UpdateProxyRequest) GetCloudflareEndpoint() string {
	if x != nil {
		return x.CloudflareEndpoint
	}
	return ""
}

func (x *UpdateProxyRequest) GetNewEndpoint() string {
	if x != nil {
		return x.NewEndpoint
	}
	return ""
}

type UpdateProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxy         *Proxy                 `protobuf:"bytes,1,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyResponse) Reset() {
	*x = UpdateProxyResponse{}
	mi := &file_docs_api_v1_types_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyResponse) ProtoMessage() {}

func (x *UpdateProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxyResponse) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{39}
}

func (x *UpdateProxyResponse) GetProxy() *Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *UpdateProxyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Proxy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CloudflareAddr string                 `protobuf:"bytes,4,opt,name=cloudflare_addr,json=cloudflareAddr,proto3" json:"cloudflare_addr,omitempty"`
	WarpInfo       *WARPInfo              `protobuf:"bytes,5,opt,name=warp_info,json=warpInfo,proto3" json:"warp_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_docs_api_v1_types_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{40}
}

func (x *Proxy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Proxy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proxy) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Proxy) GetCloudflareAddr() string {
	if x != nil {
		return x.CloudflareAddr
	}
	return ""
}

func (x *Proxy) GetWarpInfo() *WARPInfo {
	if x != nil {
		return x.WarpInfo
	}
	return nil
}

type WARPInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	HttpType       string                 `protobuf:"bytes,2,opt,name=http_type,json=httpType,proto3" json:"http_type,omitempty"`
	ServerCity     string                 `protobuf:"bytes,3,opt,name=server_city,json=serverCity,proto3" json:"server_city,omitempty"`
	ServerLocation string                 `protobuf:"bytes,4,opt,name=server_location,json=serverLocation,proto3" json:"server_location,omitempty"`
	Tls            string                 `protobuf:"bytes,5,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WARPInfo) Reset() {
	*x = WARPInfo{}
	mi := &file_docs_api_v1_types_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WARPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WARPInfo) ProtoMessage() {}

func (x *WARPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docs_api_v1_types_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WARPInfo.ProtoReflect.Descriptor instead.
func (*WARPInfo) Descriptor() ([]byte, []int) {
	return file_docs_api_v1_types_proto_rawDescGZIP(), []int{41}
}

func (x *WARPInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WARPInfo) GetHttpType() string {
	if x != nil {
		return x.HttpType
	}
	return ""
}

func (x *WARPInfo) GetServerCity() string {
	if x != nil {
		return x.ServerCity
	}
	return ""
}

func (x *WARPInfo) GetServerLocation() string {
	if x != nil {
		return x.ServerLocation
	}
	return ""
}

func (x *WARPInfo) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

var File_docs_api_v1_types_proto protoreflect.FileDescriptor

const file_docs_api_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x17docs/api/v1/types.proto\x12\x16aoyorouter.docs.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"+\n" +
	"\rSignInRequest\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\x0eSignInResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\xda\x01\n" +
	"\x15CreateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.aoyorouter.docs.api.v1.ProviderTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x04 \x01(\tR\fclientSecret\x12\x1b\n" +
	"\tuse_proxy\x18\x05 \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\x06 \x01(\tR\x05proxy\"Q\n" +
	"\x16CreateProviderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\"\xc4\x01\n" +
	"\"CreateProviderAuthorizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.aoyorouter.docs.api.v1.ProviderTypeR\x04type\x12\x1d\n" +
	"\n" +
	"custom_url\x18\x03 \x01(\tR\tcustomUrl\x12\x1b\n" +
	"\tuse_proxy\x18\a \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\b \x01(\tR\x05proxy\"\xd9\x01\n" +
	"#CreateProviderAuthorizationResponse\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\x12\x1b\n" +
	"\tuser_code\x18\x05 \x01(\tR\buserCode\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x05R\texpiresIn\"\xcc\x01\n" +
	"$CompleteProviderAuthorizationRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\x128\n" +
	"\x04type\x18\x04 \x01(\x0e2$.aoyorouter.docs.api.v1.ProviderTypeR\x04type\x12\x1b\n" +
	"\tuse_proxy\x18\x03 \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\x05 \x01(\tR\x05proxy\"p\n" +
	"%GetProviderAuthorizationStatusRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tuse_proxy\x18\x02 \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\x03 \x01(\tR\x05proxy\"t\n" +
	"#ProviderAuthorizationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"|\n" +
	"\x13ProviderQuotaWindow\x12!\n" +
	"\fused_percent\x18\x01 \x01(\x01R\vusedPercent\x12\x1b\n" +
	"\tresets_at\x18\x02 \x01(\tR\bresetsAt\x12%\n" +
	"\x0ewindow_minutes\x18\x03 \x01(\x05R\rwindowMinutes\"\xd4\x01\n" +
	"\rProviderQuota\x12E\n" +
	"\aprimary\x18\x01 \x01(\v2+.aoyorouter.docs.api.v1.ProviderQuotaWindowR\aprimary\x12I\n" +
	"\tsecondary\x18\x02 \x01(\v2+.aoyorouter.docs.api.v1.ProviderQuotaWindowR\tsecondary\x12\x1b\n" +
	"\tplan_type\x18\x03 \x01(\tR\bplanType\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9a\x02\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.aoyorouter.docs.api.v1.ProviderTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12;\n" +
	"\x05quota\x18\x06 \x01(\v2%.aoyorouter.docs.api.v1.ProviderQuotaR\x05quota\x12\x1b\n" +
	"\tuse_proxy\x18\a \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\b \x01(\tR\x05proxy\"5\n" +
	"\x12GetProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"S\n" +
	"\x13GetProviderResponse\x12<\n" +
	"\bprovider\x18\x01 \x01(\v2 .aoyorouter.docs.api.v1.ProviderR\bprovider\"\x19\n" +
	"\x17GetProvidersListRequest\"Z\n" +
	"\x18GetProvidersListResponse\x12>\n" +
	"\tproviders\x18\x01 \x03(\v2 .aoyorouter.docs.api.v1.ProviderR\tproviders\"\xfb\x01\n" +
	"\x15UpdateProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.aoyorouter.docs.api.v1.ProviderTypeR\x04type\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12\x1b\n" +
	"\tuse_proxy\x18\x06 \x01(\bR\buseProxy\x12\x14\n" +
	"\x05proxy\x18\a \x01(\tR\x05proxy\"0\n" +
	"\x16UpdateProviderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"8\n" +
	"\x15DeleteProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"0\n" +
	"\x16DeleteProviderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"D\n" +
	"\x13CreateApiKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bis_admin\x18\x02 \x01(\tR\aisAdmin\"e\n" +
	"\x14CreateApiKeyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\tR\bapiKeyId\"3\n" +
	"\x13DeleteApiKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\".\n" +
	"\x14DeleteApiKeyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"j\n" +
	"\x11EditApiKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\x127\n" +
	"\aapi_key\x18\x02 \x01(\v2\x1e.aoyorouter.docs.api.v1.ApiKeyR\x06apiKey\",\n" +
	"\x12EditApiKeyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x16\n" +
	"\x14GetApiKeyListRequest\"R\n" +
	"\x15GetApiKeyListResponse\x129\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x1e.aoyorouter.docs.api.v1.ApiKeyR\aapiKeys\"\xef\x02\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\tR\aisAdmin\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12!\n" +
	"\fquota_setted\x18\x05 \x01(\bR\vquotaSetted\x12'\n" +
	"\x0freserved_tokens\x18\x06 \x01(\x03R\x0ereservedTokens\x12@\n" +
	"\x0equota_reset_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fquotaResetAt\x12\\\n" +
	"\x14quota_reset_strategy\x18\b \x01(\x0e2*.aoyorouter.docs.api.v1.QuotaResetStrategyR\x12quotaResetStrategy\x12\x1d\n" +
	"\n" +
	"quota_used\x18\t \x01(\x03R\tquotaUsed\"\xd7\x03\n" +
	"\bLogEntry\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12\x18\n" +
	"\alatency\x18\x03 \x01(\x03R\alatency\x12!\n" +
	"\finput_tokens\x18\x04 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\x12#\n" +
	"\rcached_tokens\x18\a \x01(\x03R\fcachedTokens\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12)\n" +
	"\x10reasoning_effort\x18\t \x01(\tR\x0freasoningEffort\x12\x16\n" +
	"\x06failed\x18\n" +
	" \x01(\bR\x06failed\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12=\n" +
	"\frequest_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"C\n" +
	"\x13GetUsageLogsRequest\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"=\n" +
	"\x1dGetProviderLogsByKeyIDRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\"y\n" +
	"\x1eGetProviderLogsByKeyIDResponse\x124\n" +
	"\x04logs\x18\x01 \x03(\v2 .aoyorouter.docs.api.v1.LogEntryR\x04logs\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x03R\vtotalTokens\"L\n" +
	"\x14GetUsageLogsResponse\x124\n" +
	"\x04logs\x18\x01 \x03(\v2 .aoyorouter.docs.api.v1.LogEntryR\x04logs\"\x13\n" +
	"\x11GetProxiesRequest\"\xa5\x01\n" +
	"\x12GetProxiesResponse\x127\n" +
	"\aproxies\x18\x01 \x03(\v2\x1d.aoyorouter.docs.api.v1.ProxyR\aproxies\x12V\n" +
	"\x13available_endpoints\x18\x02 \x03(\v2%.aoyorouter.docs.api.v1.ProxyEndpointR\x12availableEndpoints\"5\n" +
	"\rProxyEndpoint\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x10\n" +
	"\x03rtt\x18\x02 \x01(\tR\x03rtt\"\x83\x01\n" +
	"\x12UpdateProxyRequest\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12/\n" +
	"\x13cloudflare_endpoint\x18\x03 \x01(\tR\x12cloudflareEndpoint\x12!\n" +
	"\fnew_endpoint\x18\x04 \x01(\tR\vnewEndpoint\"b\n" +
	"\x13UpdateProxyResponse\x123\n" +
	"\x05proxy\x18\x01 \x01(\v2\x1d.aoyorouter.docs.api.v1.ProxyR\x05proxy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa5\x01\n" +
	"\x05Proxy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12'\n" +
	"\x0fcloudflare_addr\x18\x04 \x01(\tR\x0ecloudflareAddr\x12=\n" +
	"\twarp_info\x18\x05 \x01(\v2 .aoyorouter.docs.api.v1.WARPInfoR\bwarpInfo\"\x93\x01\n" +
	"\bWARPInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1b\n" +
	"\thttp_type\x18\x02 \x01(\tR\bhttpType\x12\x1f\n" +
	"\vserver_city\x18\x03 \x01(\tR\n" +
	"serverCity\x12'\n" +
	"\x0fserver_location\x18\x04 \x01(\tR\x0eserverLocation\x12\x10\n" +
	"\x03tls\x18\x05 \x01(\tR\x03tls*\xcd\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_CUSTOM\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_OPENAI\x10\x02\x12\x1b\n" +
	"\x17PROVIDER_TYPE_ANTHROPIC\x10\x03\x12\x16\n" +
	"\x12PROVIDER_TYPE_KIMI\x10\x04\x12\x16\n" +
	"\x12PROVIDER_TYPE_GROK\x10\x05\x12\x1d\n" +
	"\x19PROVIDER_TYPE_ANTIGRAVITY\x10\x06*\x82\x02\n" +
	"\x12QuotaResetStrategy\x12$\n" +
	" QUOTA_RESET_STRATEGY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cQUOTA_RESET_STRATEGY_MINUTES\x10\x01\x12\x1f\n" +
	"\x1bQUOTA_RESET_STRATEGY_HOURLY\x10\x02\x12\x1e\n" +
	"\x1aQUOTA_RESET_STRATEGY_DAILY\x10\x03\x12\x1f\n" +
	"\x1bQUOTA_RESET_STRATEGY_WEEKLY\x10\x04\x12 \n" +
	"\x1cQUOTA_RESET_STRATEGY_MONTHLY\x10\x05\x12 \n" +
	"\x1cQUOTA_RESET_STRATEGY_FOREVER\x10\x06BAZ?github.com/yawaflua/aoyorouter/pkg/pb/api/aoyorouter;aoyorouterb\x06proto3"

var (
	file_docs_api_v1_types_proto_rawDescOnce sync.Once
	file_docs_api_v1_types_proto_rawDescData []byte
)

func file_docs_api_v1_types_proto_rawDescGZIP() []byte {
	file_docs_api_v1_types_proto_rawDescOnce.Do(func() {
		file_docs_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_api_v1_types_proto_rawDesc), len(file_docs_api_v1_types_proto_rawDesc)))
	})
	return file_docs_api_v1_types_proto_rawDescData
}

var file_docs_api_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_docs_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_docs_api_v1_types_proto_goTypes = []any{
	(ProviderType)(0),                             // 0: aoyorouter.docs.api.v1.ProviderType
	(QuotaResetStrategy)(0),                       // 1: aoyorouter.docs.api.v1.QuotaResetStrategy
	(*HealthCheckResponse)(nil),                   // 2: aoyorouter.docs.api.v1.HealthCheckResponse
	(*SignInRequest)(nil),                         // 3: aoyorouter.docs.api.v1.SignInRequest
	(*SignInResponse)(nil),                        // 4: aoyorouter.docs.api.v1.SignInResponse
	(*CreateProviderRequest)(nil),                 // 5: aoyorouter.docs.api.v1.CreateProviderRequest
	(*CreateProviderResponse)(nil),                // 6: aoyorouter.docs.api.v1.CreateProviderResponse
	(*CreateProviderAuthorizationRequest)(nil),    // 7: aoyorouter.docs.api.v1.CreateProviderAuthorizationRequest
	(*CreateProviderAuthorizationResponse)(nil),   // 8: aoyorouter.docs.api.v1.CreateProviderAuthorizationResponse
	(*CompleteProviderAuthorizationRequest)(nil),  // 9: aoyorouter.docs.api.v1.CompleteProviderAuthorizationRequest
	(*GetProviderAuthorizationStatusRequest)(nil), // 10: aoyorouter.docs.api.v1.GetProviderAuthorizationStatusRequest
	(*ProviderAuthorizationStatusResponse)(nil),   // 11: aoyorouter.docs.api.v1.ProviderAuthorizationStatusResponse
	(*ProviderQuotaWindow)(nil),                   // 12: aoyorouter.docs.api.v1.ProviderQuotaWindow
	(*ProviderQuota)(nil),                         // 13: aoyorouter.docs.api.v1.ProviderQuota
	(*Provider)(nil),                              // 14: aoyorouter.docs.api.v1.Provider
	(*GetProviderRequest)(nil),                    // 15: aoyorouter.docs.api.v1.GetProviderRequest
	(*GetProviderResponse)(nil),                   // 16: aoyorouter.docs.api.v1.GetProviderResponse
	(*GetProvidersListRequest)(nil),               // 17: aoyorouter.docs.api.v1.GetProvidersListRequest
	(*GetProvidersListResponse)(nil),              // 18: aoyorouter.docs.api.v1.GetProvidersListResponse
	(*UpdateProviderRequest)(nil),                 // 19: aoyorouter.docs.api.v1.UpdateProviderRequest
	(*UpdateProviderResponse)(nil),                // 20: aoyorouter.docs.api.v1.UpdateProviderResponse
	(*DeleteProviderRequest)(nil),                 // 21: aoyorouter.docs.api.v1.DeleteProviderRequest
	(*DeleteProviderResponse)(nil),                // 22: aoyorouter.docs.api.v1.DeleteProviderResponse
	(*CreateApiKeyRequest)(nil),                   // 23: aoyorouter.docs.api.v1.CreateApiKeyRequest
	(*CreateApiKeyResponse)(nil),                  // 24: aoyorouter.docs.api.v1.CreateApiKeyResponse
	(*DeleteApiKeyRequest)(nil),                   // 25: aoyorouter.docs.api.v1.DeleteApiKeyRequest
	(*DeleteApiKeyResponse)(nil),                  // 26: aoyorouter.docs.api.v1.DeleteApiKeyResponse
	(*EditApiKeyRequest)(nil),                     // 27: aoyorouter.docs.api.v1.EditApiKeyRequest
	(*EditApiKeyResponse)(nil),                    // 28: aoyorouter.docs.api.v1.EditApiKeyResponse
	(*GetApiKeyListRequest)(nil),                  // 29: aoyorouter.docs.api.v1.GetApiKeyListRequest
	(*GetApiKeyListResponse)(nil),                 // 30: aoyorouter.docs.api.v1.GetApiKeyListResponse
	(*ApiKey)(nil),                                // 31: aoyorouter.docs.api.v1.ApiKey
	(*LogEntry)(nil),                              // 32: aoyorouter.docs.api.v1.LogEntry
	(*GetUsageLogsRequest)(nil),                   // 33: aoyorouter.docs.api.v1.GetUsageLogsRequest
	(*GetProviderLogsByKeyIDRequest)(nil),         // 34: aoyorouter.docs.api.v1.GetProviderLogsByKeyIDRequest
	(*GetProviderLogsByKeyIDResponse)(nil),        // 35: aoyorouter.docs.api.v1.GetProviderLogsByKeyIDResponse
	(*GetUsageLogsResponse)(nil),                  // 36: aoyorouter.docs.api.v1.GetUsageLogsResponse
	(*GetProxiesRequest)(nil),                     // 37: aoyorouter.docs.api.v1.GetProxiesRequest
	(*GetProxiesResponse)(nil),                    // 38: aoyorouter.docs.api.v1.GetProxiesResponse
	(*ProxyEndpoint)(nil),                         // 39: aoyorouter.docs.api.v1.ProxyEndpoint
	(*UpdateProxyRequest)(nil),                    // 40: aoyorouter.docs.api.v1.UpdateProxyRequest
	(*UpdateProxyResponse)(nil),                   // 41: aoyorouter.docs.api.v1.UpdateProxyResponse
	(*Proxy)(nil),                                 // 42: aoyorouter.docs.api.v1.Proxy
	(*WARPInfo)(nil),                              // 43: aoyorouter.docs.api.v1.WARPInfo
	(*timestamppb.Timestamp)(nil),                 // 44: google.protobuf.Timestamp
}
var file_docs_api_v1_types_proto_depIdxs = []int32{
	0,  // 0: aoyorouter.docs.api.v1.CreateProviderRequest.type:type_name -> aoyorouter.docs.api.v1.ProviderType
	0,  // 1: aoyorouter.docs.api.v1.CreateProviderAuthorizationRequest.type:type_name -> aoyorouter.docs.api.v1.ProviderType
	0,  // 2: aoyorouter.docs.api.v1.CompleteProviderAuthorizationRequest.type:type_name -> aoyorouter.docs.api.v1.ProviderType
	12, // 3: aoyorouter.docs.api.v1.ProviderQuota.primary:type_name -> aoyorouter.docs.api.v1.ProviderQuotaWindow
	12, // 4: aoyorouter.docs.api.v1.ProviderQuota.secondary:type_name -> aoyorouter.docs.api.v1.ProviderQuotaWindow
	0,  // 5: aoyorouter.docs.api.v1.Provider.type:type_name -> aoyorouter.docs.api.v1.ProviderType
	13, // 6: aoyorouter.docs.api.v1.Provider.quota:type_name -> aoyorouter.docs.api.v1.ProviderQuota
	14, // 7: aoyorouter.docs.api.v1.GetProviderResponse.provider:type_name -> aoyorouter.docs.api.v1.Provider
	14, // 8: aoyorouter.docs.api.v1.GetProvidersListResponse.providers:type_name -> aoyorouter.docs.api.v1.Provider
	0,  // 9: aoyorouter.docs.api.v1.UpdateProviderRequest.type:type_name -> aoyorouter.docs.api.v1.ProviderType
	31, // 10: aoyorouter.docs.api.v1.EditApiKeyRequest.api_key:type_name -> aoyorouter.docs.api.v1.ApiKey
	31, // 11: aoyorouter.docs.api.v1.GetApiKeyListResponse.api_keys:type_name -> aoyorouter.docs.api.v1.ApiKey
	44, // 12: aoyorouter.docs.api.v1.ApiKey.quota_reset_at:type_name -> google.protobuf.Timestamp
	1,  // 13: aoyorouter.docs.api.v1.ApiKey.quota_reset_strategy:type_name -> aoyorouter.docs.api.v1.QuotaResetStrategy
	44, // 14: aoyorouter.docs.api.v1.LogEntry.request_time:type_name -> google.protobuf.Timestamp
	44, // 15: aoyorouter.docs.api.v1.LogEntry.created_at:type_name -> google.protobuf.Timestamp
	32, // 16: aoyorouter.docs.api.v1.GetProviderLogsByKeyIDResponse.logs:type_name -> aoyorouter.docs.api.v1.LogEntry
	32, // 17: aoyorouter.docs.api.v1.GetUsageLogsResponse.logs:type_name -> aoyorouter.docs.api.v1.LogEntry
	42, // 18: aoyorouter.docs.api.v1.GetProxiesResponse.proxies:type_name -> aoyorouter.docs.api.v1.Proxy
	39, // 19: aoyorouter.docs.api.v1.GetProxiesResponse.available_endpoints:type_name -> aoyorouter.docs.api.v1.ProxyEndpoint
	42, // 20: aoyorouter.docs.api.v1.UpdateProxyResponse.proxy:type_name -> aoyorouter.docs.api.v1.Proxy
	43, // 21: aoyorouter.docs.api.v1.Proxy.warp_info:type_name -> aoyorouter.docs.api.v1.WARPInfo
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_docs_api_v1_types_proto_init() }
func file_docs_api_v1_types_proto_init() {
	if File_docs_api_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_api_v1_types_proto_rawDesc), len(file_docs_api_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docs_api_v1_types_proto_goTypes,
		DependencyIndexes: file_docs_api_v1_types_proto_depIdxs,
		EnumInfos:         file_docs_api_v1_types_proto_enumTypes,
		MessageInfos:      file_docs_api_v1_types_proto_msgTypes,
	}.Build()
	File_docs_api_v1_types_proto = out.File
	file_docs_api_v1_types_proto_goTypes = nil
	file_docs_api_v1_types_proto_depIdxs = nil
}
